name: build-and-deploy

on:
  push:
    branches:
      - main
      - "release/**"

env:
  INITIAL_VERSION: 1.0.0

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test
        run: |
          npm install
          npm run test

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: coverage

  calculate-version:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github-tag-action.outputs.new_tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: github-tag-action
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch

  build:
    needs: calculate-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update version
        env:
          ADJUSTED_VERSION: ${{needs.calculate-version.outputs.new_tag}}
        run: npm version $ADJUSTED_VERSION --no-git-tag-version

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
